### PR TITLE
Fixed token selector duplicating items

### LINKED ISSUE #632: Token List is acting funky
**Describe the bug**

Screen Shot 2022-01-06 at 7 05 26 PM

**To Reproduce**

- [ ] yarn chain
- [ ] yarn deploy
- [ ] yarn start
- [ ] navigate to 'Hints' tab
- [ ] use the Pick a token select list and scroll

### PR DESCRIPTION
**Pull request by MimmDev**
fixes #632 

The issue was caused by `listOfTokens` containing tokens which have duplicate symbols (CMI, for example). As these symbols were not unique but used as keys for the `Option` components, it caused React to duplicate/overwrite list items while scrolling.

### CODE REVIEW

File: packages/react-app/src/views/Hints.jsx [hunk 1]
```diff
@@ -113,7 +113,7 @@ export default function Hints({ yourLocalBalance, mainnetProvider, price, addres
           optionFilterProp="children"
         >
           {listOfTokens.map(token => (
-            <Option key={token.symbol} value={token.symbol}>
+            <Option key={token.address} value={token.symbol}>
```
Comment (kamikazebr) [inline packages/react-app/src/views/Hints.jsx:116]: Nice catch! Idk if is to much, but you could even concatenate symbol more address there to even avoid address conflict. (i know looks impossible that to happend). Up to you.

**Review by kamikazebr — APPROVED** [review]
Nice catch!

File: packages/react-app/src/views/Hints.jsx (hunk 1 above)
Comment (codenamejason) [reply packages/react-app/src/views/Hints.jsx:116]: I updated to be key={token.address + "_" + token.symbol}

**Review by codenamejason — APPROVED** [review]
